WIP: Group Advanced Settings - Change Path
phac-nml/irida-next pull request #115
Opened 2023-06-06 14:27 UTC by ksierks

2023-07-05 19:21 UTC, ksierks commented
> As per our conversation last week, could you please update the structure/styling of the Groups Settings page to match the structure/styling of the Project Settings page that was recently merged in.
> 
> e.g. ![image](https://user-images.githubusercontent.com/492127/251174616-555059c5-e3a7-4a33-9780-0f5cd9d643f4.png)

Please see 1583ce658ef83dc19b21d348bdf154d431135a7d.

2023-07-07 14:32 UTC, joshsadam commented
Just a quick comment on the overall appearance:

![](https://github.com/phac-nml/irida-next/assets/11295750/85bcf6ba-e1d6-4045-95b4-592406be0936)

1.  There are different gaps under all the buttons, I prefer the gap under button 1.
2.  Buttons have different heights, this might be fixed in my updated button PR #131 and could be caused by something in the class definition that currently exists (i.e. I don't think it is something that you did, but needs to be addressed).  Maybe we should hold on this PR until the button on is merged in to main. 
    1.  1 is 40px
    2.  2 is 42px
    3.  3 is 36px

2023-07-07 14:32 UTC, joshsadam commented
Just a quick comment on the overall appearance:

![](https://github.com/phac-nml/irida-next/assets/11295750/85bcf6ba-e1d6-4045-95b4-592406be0936)

1.  There are different gaps under all the buttons, I prefer the gap under button 1.
2.  Buttons have different heights, this might be fixed in my updated button PR #131 and could be caused by something in the class definition that currently exists (i.e. I don't think it is something that you did, but needs to be addressed).  Maybe we should hold on this PR until the button on is merged in to main. 
    1.  1 is 40px
    2.  2 is 42px
    3.  3 is 36px

2023-07-07 15:12 UTC, ericenns requested changes
Reviewing #75 the changes here don't quite match what was requested.

Specifically title in the card should be updated to `Change group URL`, along with the submitting button text and the parent namespace should not be allowed to be changed as that is covered in the transferring group which you have a separate PR for.

See image below for what it looks like in gitlab, which our redesign is based off of.

![MicrosoftTeams-image (6)](https://github.com/phac-nml/irida-next/assets/492127/41076949-e6aa-4d80-bd43-87d0f8ed21f5)

Also, after updating the look please make sure to update the screenshots in the PR description as we want to make sure these are always up to date with the latest changes.

2023-07-07 15:13 UTC, joshsadam requested changes
One small change here.  I will take a look again once the other issues are addressed.  Thanks @ksierks

2023-07-07 17:54 UTC, ksierks commented
> Reviewing #75 the changes here don't quite match what was requested.
> 
> Specifically title in the card should be updated to `Change group URL`, along with the submitting button text and the parent namespace should not be allowed to be changed as that is covered in the transferring group which you have a separate PR for.
> 
> See image below for what it looks like in gitlab, which our redesign is based off of.
> 
> ![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/492127/251783419-41076949-e6aa-4d80-bd43-87d0f8ed21f5.png)
> 
> Also, after updating the look please make sure to update the screenshots in the PR description as we want to make sure these are always up to date with the latest changes.

I was so focused on moving the existing change path while not breaking subgroups. That makes more sense. Working on fixing it.

2023-07-10 18:58 UTC, ksierks commented
> > Reviewing #75 the changes here don't quite match what was requested.
> > Specifically title in the card should be updated to `Change group URL`, along with the submitting button text and the parent namespace should not be allowed to be changed as that is covered in the transferring group which you have a separate PR for.
> > See image below for what it looks like in gitlab, which our redesign is based off of.
> > ![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/492127/251783419-41076949-e6aa-4d80-bd43-87d0f8ed21f5.png)
> > Also, after updating the look please make sure to update the screenshots in the PR description as we want to make sure these are always up to date with the latest changes.
> 
> I was so focused on moving the existing change path while not breaking subgroups. That makes more sense. Working on fixing it.

I'm unsure how exact you want it to look like GitLab's Change URL. I left the form label for accessibility and the default button.  Most importantly, the parent group drop-down is removed and I also added the tooltip and form field title. Also, the screenshot above has been updated. Hope this looks okay.

![Screenshot from 2023-07-10 13-35-55](https://github.com/phac-nml/irida-next/assets/325703/2ab946d9-9f6d-4595-80d5-e6e970fc2c30)

2023-07-10 19:02 UTC, ksierks commented on app/views/groups/_path_form_fields.html.erb
> +            dark:text-gray-200
I think this was quickly copied from _project_namespace_fields.erb

2023-07-12 14:05 UTC, ericenns requested changes
Just noting our conversation regarding a few more changes:

* change the submit button to red
* remove the label for `parent_id` and the hidden `parent_id` input
* reduce to single form-field with prefixed span showing root url, and move class to input called `prefixed` (following example set out in select.prefixed in group creation form)
* fix css width issue when input has errors
* fix wrong url for path when attempting to update group to existing path causes error
  * note: this issue is existing and was not introduced in this pr

2023-07-12 19:36 UTC, ericenns approved these changes
Looks good to me! Thanks for making all the changes

2023-07-12 19:36 UTC, merged