Add group to group
phac-nml/irida-next pull request #127
Opened 2023-06-28 20:35 UTC by deepsidhu85

## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR adds a new model `GroupGroupLink` which will be used to add a group to another group. This is 1 of many prs to get the group to group links working. This PR includes the model, db setup, and model testing. Future PRs will address the service to share, as well as the UI.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated
  the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2023-07-13 13:37 UTC, ericenns requested changes
Generally this is looking really great, just a few suggestions and questions below.

2023-07-13 14:26 UTC, deepsidhu85 commented on app/models/group.rb
> +          group.self_and_ancestors.reorder(nil).select(:id)
Updated in 355be769f822868465b5b434d32fa05f450b545d

2023-07-13 14:26 UTC, deepsidhu85 commented on app/models/group.rb
> +      GroupGroupLink.where(shared_group_id: group.ancestors.reorder(nil).select(:id))
Removed reorder and updated to use ancestor_ids in 355be769f822868465b5b434d32fa05f450b545d

2023-07-19 16:04 UTC, deepsidhu85 commented
Replaced with #133

2023-07-19 16:04 UTC, closed without merging