GraphQL: Project Type
phac-nml/irida-next pull request #136
Opened 2023-07-17 19:07 UTC by ericenns

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated
  the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2023-07-18 21:28 UTC, JeffreyThiessen submitted a review, later dismissed
Code looks good and everything looks to be working as intended.

2023-07-19 16:13 UTC, deepsidhu85 requested changes
This looks good. Just a few comments below for the `description` of a project and namespace

2023-07-20 17:08 UTC, ericenns commented on app/graphql/types/namespace.rb
> +    field :description, String, null: false, description: 'Description of the namespace.'
fixed in eeb311f

2023-07-20 17:08 UTC, ericenns commented on app/graphql/types/project_type.rb
> +    field :description, String, null: false, description: 'Description of the project.'
fixed in eeb311f

2023-07-21 16:18 UTC, deepsidhu85 commented on app/graphql/types/project_type.rb
> +    field :description, String, null: false, description: 'Description of the project.'
Thanks!

2023-07-21 16:18 UTC, deepsidhu85 commented on app/graphql/types/namespace.rb
> +    field :description, String, null: false, description: 'Description of the namespace.'
Thanks!

2023-07-21 16:18 UTC, deepsidhu85 approved these changes

2023-07-21 16:22 UTC, merged