Member create modal
phac-nml/irida-next pull request #170
Opened 2023-09-07 22:11 UTC by deepsidhu85

## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR adds functionality to add a member to a group/project using a modal and to use turbo_stream.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Login as any user
2. Visit a groups members page
3. Click the `Add New Member` button
4. A modal should pop up for you to select a user and their access level
5. Select a user and their access level
6. Click the `Add member to group` button
7. The table and pagination should update to include this user
8. Verify the same functionality for a project

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [X] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2023-09-08 10:37 UTC, joshsadam commented
This is still doing a full page fetch on the project add new member 
![image](https://github.com/phac-nml/irida-next/assets/11295750/558924f9-ba6a-4799-aae7-2924dceff630)

2023-09-08 11:10 UTC, deepsidhu85 commented
> This is still doing a full page fetch on the project add new member, it is working properly on the groups though. ![image](https://user-images.githubusercontent.com/11295750/266583418-558924f9-ba6a-4799-aae7-2924dceff630.png)

I can't seem to replicate it..these are what my network tab looks like for both group members new and project members new

![image](https://github.com/phac-nml/irida-next/assets/25466211/b271a927-3303-47a8-9155-e8d914e6d5e1)

![image](https://github.com/phac-nml/irida-next/assets/25466211/71ff492e-5c07-4d4c-a8bf-65156d09f745)

2023-09-08 12:25 UTC, joshsadam commented
I was actually wrong before (not in your favour though), the response to both is returning a full HTML page.  Look at the network tab you showed me above, click on the first call named `new` and look at the response, it's the full page.  This is turbo's normal action and gives you the entire page and then just replaces what it wants.  What I think you are trying to do is to get the partial that just has the dialogue contents in it.

2023-09-08 13:00 UTC, deepsidhu85 commented
> I was actually wrong before (not in your favour though), the response to both is returning a full HTML page on both project and groups. Look at the network tab you showed me above, click on the first call named `new` and look at the response, it's the full page. This is turbo's normal action and gives you the entire page and then just replaces what it wants. What I think you are trying to do is to get the partial that just has the dialogue contents in it.

As discussed the purpose of this PR was to open the create modal via a server call and not have the new page load on a separate page. The request to create the member is what is being sent via a turbo stream request

2023-09-08 13:53 UTC, joshsadam requested changes
Overall, from what I see, this looks good.  I would still like to see the dialogue being rendered using a turbo_stream instead of a full-page request.  Good work Deep.

2023-09-08 13:53 UTC, joshsadam commented on app/components/viral/dialog/header_component.html.erb
> +  <h1 class="dialog--title">
**nitpick:** Why did you change this to an h1 tag? There should only ever be 1 h1 tag on a page, and the title of a dialogue is probably not that.  The flowbite documentation has it as an h3.

2023-09-08 14:20 UTC, joshsadam commented on app/components/viral/dialog/header_component.html.erb
> +  <h1 class="dialog--title">
Apparently, you are correct.  Thanks for updating this.

2023-09-08 14:55 UTC, deepsidhu85 commented
> Overall, from what I see, this looks good. I would still like to see the dialogue being rendered using a turbo_stream instead of a full-page request. Good work Deep.

Thanks! I updated the modals to be rendered via turbo_stream in 4ba6e11798a68b9286ba3c74ce734d70ba5e1eb7

2023-09-11 13:40 UTC, ericenns approved these changes
Looks good to me! I tested it all out and it is working as expected

2023-09-11 13:52 UTC, joshsadam approved these changes

2023-09-11 13:52 UTC, merged