WIP: Edit project fix
phac-nml/irida-next pull request #197
Opened 2023-09-20 14:59 UTC by ksierks

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2023-09-22 21:17 UTC, deepsidhu85 commented
Just leaving a general comment on the PR of the changes we discussed:

1) Use html sytnax to create a turbo frame around the breadcrumbs so we don't need to use a helper in the component

2) After setting the `change_path submit button to not use turbo when the path was updated but there was an error it caused the url to change with the `/-/edit` removed from it. Update this to use turbo and the update method in projects_controller to only respond to turbo_stream

3) Since the breadcrumbs are now in a turbo frame the navigation needs to be updated to it happens "outside" of the turbo frame. This can be updated in the breadcrumb component where the link is created to set the data: {turbo_frame: "_top"} for each of the link_to tags

4) Looks like I accidentally deleted the review I had left, but it was just to updated the name of the form_fields partial to a clearer name

2023-09-25 13:14 UTC, joshsadam approved these changes
Thanks @ksierks this appears to work the way it is supposed to.  Once @ deepsidhu85 gives it the thumbs up, this is good to go.  We still may want to break each section of the settings page out into its own turbo frame at some point, so you don't need to return it all.

2023-09-25 13:40 UTC, ksierks commented
> Just leaving a general comment on the PR of the changes we discussed and that were made:
> 
> 1. Use html sytnax to create a turbo frame around the breadcrumbs so we don't need to use a helper in the component
> 2. After setting the `change_path submit button to not use turbo when the path was updated but there was an error it caused the url to change with the `/-/edit` removed from it. Update this to use turbo and the update method in projects_controller to only respond to turbo_stream
> 3. Since the breadcrumbs are now in a turbo frame the navigation needs to be updated to it happens "outside" of the turbo frame. This can be updated in the breadcrumb component where the link is created to set the data: {turbo_frame: "_top"} for each of the link_to tags
> 4. Looks like I accidentally deleted the review I had left, but it was just to updated the name of the form_fields partial to a clearer name

To address #4, I renamed the form `_edit_name_and_description_form.html.erb` like in the groups PR. Please see aaea28541ed40a2e45c9937e8e0a812428e6cb2d.

2023-09-25 14:33 UTC, deepsidhu85 requested changes
This all looks great. Just a test to add below

2023-09-25 14:33 UTC, deepsidhu85 commented on test/system/projects_test.rb
>      fill_in I18n.t(:'activerecord.attributes.namespaces/project_namespace.name'), with: project_name
Can I get you to add a test for a successful path change? We will want to test if the url updated correctly and assert that the success text was displayed in the flash

2023-09-25 15:32 UTC, deepsidhu85 commented on test/system/projects_test.rb
>      fill_in I18n.t(:'activerecord.attributes.namespaces/project_namespace.name'), with: project_name
You are correct! Totally missed it. Thanks

2023-09-25 15:32 UTC, deepsidhu85 approved these changes

2023-09-25 15:34 UTC, merged