Update Group Samples Table
phac-nml/irida-next pull request #351
Opened 2024-01-02 20:21 UTC by ksierks

## What does this PR do and why?
_Describe in detail what your merge request does and why._
Fixes #266.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-01-03 15:27 UTC, joshsadam requested changes
This works exactly as it is supposed to.  I just have one request and that this to add a test for the abbreviated path.  Great work.

2024-01-03 18:02 UTC, ChrisHuynh333 submitted a review, later dismissed
This works as expected and looks good to me. Only thing is with the abbreviated path, would it be more beneficial to have maybe 3 characters so it's a little more recognizable at a glance for the user? Unless we expect lots of namespace nesting by users or the table to be further crowded (metadata?), then it's understandable to have it as a single char. I'll let someone else have final word on this, just a thought!

2024-01-03 21:02 UTC, ericenns commented on app/models/concerns/routable.rb
> +  def abbreviated_path
I agree, specifically this should be in a model test.

2024-01-03 23:06 UTC, ksierks commented on app/models/concerns/routable.rb
> +  def abbreviated_path
Is this sufficient? Please see 9bd1e197e5d30849c2580cba108f3ba26f0ae89d.

2024-01-03 23:09 UTC, ksierks commented
> This works as expected and looks good to me. Only thing is with the abbreviated path, would it be more beneficial to have maybe 3 characters so it's a little more recognizable at a glance for the user? Unless we expect lots of namespace nesting by users or the table to be further crowded (metadata?), then it's understandable to have it as a single char. I'll let someone else have final word on this, just a thought!

It makes no difference to me. I only used the first character as that is what was described in the issue. Please let me know if I should change it to 3 characters.

2024-01-08 17:22 UTC, ericenns commented
> > This works as expected and looks good to me. Only thing is with the abbreviated path, would it be more beneficial to have maybe 3 characters so it's a little more recognizable at a glance for the user? Unless we expect lots of namespace nesting by users or the table to be further crowded (metadata?), then it's understandable to have it as a single char. I'll let someone else have final word on this, just a thought!
> 
> It makes no difference to me. I only used the first character as that is what was described in the issue. Please let me know if I should change it to 3 characters.

We are going to stick with 1 character to represent each higher level, as the full hierarchy is viewable on mouse over.

2024-01-08 19:29 UTC, ksierks commented on app/models/concerns/routable.rb
> +  def abbreviated_path
And 6c9ebdb425355a3d4152913c5e4995a7c1a3cecd.

2024-01-08 19:35 UTC, joshsadam commented on app/models/concerns/routable.rb
> +  def abbreviated_path
Thanks

2024-01-08 19:36 UTC, joshsadam approved these changes
This looks good to me.

2024-01-09 13:36 UTC, ericenns approved these changes
This looks good to me!

2024-01-09 13:36 UTC, merged