Add updated_at field to metadata_provenance
phac-nml/irida-next pull request #364
Opened 2024-01-09 21:04 UTC by ChrisHuynh333

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-01-09 22:56 UTC, deepsidhu85 approved these changes
Looks good to me!

2024-01-10 15:07 UTC, ericenns requested changes
Just comments on setting up the data for the tests.

2024-01-10 15:07 UTC, ericenns commented on test/services/samples/metadata/update_service_test.rb
**nitpick (blocking):** Can you please update the `text/fixtures/samples.yml` to setup the `metadata` and `metadata_provenance` for these tests instead of doing it in the `test` as the way it is done now those values are not persisted to the database so it isn't really testing it accurately. I did also notice that all the setup was the same so it makes sense to have it in the fixtures file.

2024-01-10 15:45 UTC, ChrisHuynh333 commented on test/services/samples/metadata/update_service_test.rb
As discussed on Teams, I'll wait until [PR 339](https://github.com/phac-nml/irida-next/pull/339) is merged as I've created all the necessary test fixtures in there. Once merged, I'll adjust the tests contained here to utilize the newly merged fixtures.

2024-01-16 22:44 UTC, ChrisHuynh333 commented on test/services/samples/metadata/update_service_test.rb
This has now been updated with the tests from [PR 339](https://github.com/phac-nml/irida-next/pull/339) with `updated_at` added to `metadata_provenance`

2024-01-17 15:00 UTC, ericenns approved these changes
Looks good to me!

2024-01-17 15:21 UTC, merged