GraphQL: Sample Metadata Field Query
phac-nml/irida-next pull request #377
Opened 2024-01-18 14:52 UTC by ericenns

## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR updates SampleType in the GraphQL API to include a Metadata field, to access the metadata associated with a Sample.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-01-18 17:48 UTC, ChrisHuynh333 approved these changes
This works as described. Just wondering if an error should be returned for subset metadata if the key does not exist? Nothing else to add.

2024-01-18 17:56 UTC, ericenns commented
> This works as described. Just wondering if an error should be returned for subset metadata if the key does not exist? Nothing else to add.

I don't think an error is appropriate as someone may ask for `n` keys that are present in `m` samples, where they have `o` total samples. In that case the key not being contained in a sample metadata response is acceptable as `m` is < `o`.

2024-01-18 18:51 UTC, ksierks submitted a review, later dismissed
Works as described.

2024-01-18 22:49 UTC, deepsidhu85 requested changes
This looks good and working as expected. Just one comment below to add a test

2024-01-18 22:49 UTC, deepsidhu85 commented on test/graphql/samples_query_test.rb
> +  end
Can I just get you to add one more test here for the case of a user querying for a metadata key that isn't in the sample metadata

2024-01-19 14:56 UTC, deepsidhu85 commented on test/graphql/samples_query_test.rb
> +  end
Thanks!

2024-01-19 14:57 UTC, deepsidhu85 approved these changes

2024-01-19 14:57 UTC, merged