Sample cleanup job & task
phac-nml/irida-next pull request #436
Opened 2024-02-21 20:15 UTC by ksierks

## What does this PR do and why?
Created a new job and task which accepts the argument `days_old` and permanently deletes samples older than `days_old`.
Fixes #427.

## Screenshots or screen recordings
N/A

## How to set up and validate locally
1. Login to irida-next.
2. Find a sample and delete it.
3. Verify the sample was soft-deleted.
4. Open a terminal.
5. Run the command `rake samples:cleanup` or `rake samples:cleanup[n]` where n is days old.
6. Verify the sample and its attachments and workflow executions are no longer in the database.

To verify a sample was soft-deleted:
1. Open a rails console. 
2. Run the command `Sample.only_deleted`.

To verify a sample was removed from the database:
1. Open a rails console. 
2. Run the command `Sample.only.where(id:?)`.

Note: If you open a rails console and try running any of the following queries, `WHERE "samples"."deleted_at" IS NULL` is always appended to the database query. Use `Sample.only` as a workaround.
```
Sample.all.count
SELECT COUNT(*) FROM "samples" WHERE "samples"."deleted_at" IS NULL
Sample.where.not(deleted_at: nil).count
SELECT COUNT(*) FROM "samples" WHERE "samples"."deleted_at" IS NULL AND "samples"."deleted_at" IS NOT NULL
Sample.exists?(id:1419)
SELECT 1 AS one FROM "samples" WHERE "samples"."deleted_at" IS NULL AND "samples"."id" = $1
Sample.first
SELECT "samples"."id", "samples"."name", "samples"."description", "samples"."project_id", "samples"."created_at", "samples"."updated_at", "samples"."deleted_at", "samples"."metadata", "samples"."metadata_provenance", "samples"."puid" FROM "samples" WHERE "samples"."deleted_at" IS NULL ORDER BY "samples"."id" ASC LIMIT $1
```

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-02-28 13:54 UTC, ericenns requested changes
This looks good, could you please add this task to the good_job cron config. It can be found in `config/application.rb`.

2024-02-28 18:20 UTC, ksierks commented
> This looks good, could you please add this task to the good_job cron config. It can be found in `config/application.rb`.

6b13d79c4a53acf41e3f2f2669592c40647fa0a7

2024-03-08 17:57 UTC, ChrisHuynh333 approved these changes
Nothing to add, looks great!

2024-03-12 13:44 UTC, ericenns approved these changes

2024-03-12 13:44 UTC, merged