Data Export - Create Job
phac-nml/irida-next pull request #449
Opened 2024-02-28 21:16 UTC by ChrisHuynh333

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-03-19 18:18 UTC, deepsidhu85 requested changes
Just a quick comment to start to get rid of the rubocop disables

2024-03-19 18:18 UTC, deepsidhu85 commented on app/jobs/data_exports/create_job.rb
> +    def create_sample_zip(data_export) # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
This method seems to have become unnecessarily large and requires a few rubocop disables.

This method can be split up to remove all the rubocop disables by adding 2 new methods (write_attachments, and write_manifest) and moving the relevant code into the methods

- write_attachments should take params (project, sample, zip)
- write_manifest should take params (manifest, zip)

2024-03-21 00:02 UTC, JeffreyThiessen requested changes
Overall looks good. While testing I rand into an issue where the job would not run after being queue'd but I don't know if that is the code problem or something wrong on my machine.

I manually started the job with `DataExports::CreateJob.perform_now(data_export)` and it worked as expected.

My main point of feedback is the date/time stuff should be in its own helper file.

2024-03-21 15:05 UTC, ChrisHuynh333 commented on app/jobs/data_exports/create_job.rb
> +    def set_expiry
Fixed in 943a166d78713cba9304c5ce616e297fdfea44ee

2024-03-21 15:05 UTC, ChrisHuynh333 commented on app/jobs/data_exports/create_job.rb
> +    def add_holidays(days_to_check, holidays)
Fixed in 943a166d78713cba9304c5ce616e297fdfea44ee

2024-03-21 15:25 UTC, JeffreyThiessen approved these changes
Looks good

2024-03-21 16:00 UTC, deepsidhu85 commented on app/jobs/data_exports/create_job.rb
> +    def create_sample_zip(data_export) # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
Thanks!

2024-03-21 18:15 UTC, deepsidhu85 approved these changes
Looks good to me! Working as expected!

2024-03-21 18:15 UTC, merged