List samples with transfer dialog
phac-nml/irida-next pull request #480
Opened 2024-03-19 20:47 UTC by ksierks

## What does this PR do and why?
_Describe in detail what your merge request does and why._
Fixes #468.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-03-21 15:53 UTC, joshsadam requested changes
Doing the same thing as files (cloning the first two columns) won't work here.  This is what I tried:
1. I have a project of 40 (anything >20 will work)
2. Select all samples in the project
3. Open then transfer dialog, only 20 samples are displayed ☹️

2024-03-21 15:53 UTC, joshsadam commented on config/locales/en.yml
> +          description: "The following files were selected to be transferred:"
**nitpick:** This should probably read `The following samples were selected to be transfered`

2024-03-21 15:53 UTC, joshsadam commented on app/javascript/controllers/list_samples_controller.js
> +    const newTable = document.createElement("table");
**suggestion:** This table will need table headers.  Try having the table already in the dialog with the headers and have the body as a target for this controller.

2024-04-02 15:00 UTC, ksierks commented
redoing in another pr

2024-04-02 15:00 UTC, closed without merging