[ENHC0010017] Change export download to use rails_blob_path
phac-nml/irida-next pull request #616
Opened 2024-05-24 15:05 UTC by ChrisHuynh333

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-05-29 18:07 UTC, ericenns requested changes
Just a few minor comments, otherwise this is working as expected.

2024-05-29 18:07 UTC, ericenns commented on app/controllers/data_exports_controller.rb
Can you remove the reference to `download` in the before_action at the top of this file.

2024-05-29 18:07 UTC, ericenns commented on app/controllers/projects/samples/attachments_controller.rb
Can you remove the reference to `download` in the before_action at the top of this file.

2024-05-29 18:55 UTC, ChrisHuynh333 commented on app/controllers/data_exports_controller.rb
Removed in 9284422be5d0dc2b62cf4205548c94afb5994127

2024-05-30 13:30 UTC, ericenns approved these changes
Looks good to me!

2024-05-30 13:30 UTC, merged