Pipeline config/executable
phac-nml/irida-next pull request #698
Opened 2024-08-13 19:27 UTC by malchua

## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR allows an administrator of IRIDA Next to specify which versions of pipelines are not executable.
This PR relates to issue #680.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

1. Sign in
2. Select Projects on the sidebar and click on a project that is listed
3. Select Samples in the side bar and select one or two of the samples
4. Click the rocket-ship button to start creating a workflow execution
5. Compare the pipelines that are listed with the pipelines listed in `config/pipelines/pipelines.json`
6. Check to see that only the pipelines that do not have the executable option set to `false` are listed
7. Select Settings in the side bar and select Automated Workflow Executions from the drop-down menu
8. Click on New automated workflow execution button
9. Compare the pipelines that are listed with the pipelines listed in `config/pipelines/pipelines.json`
10. Check to see that only the pipelines with `automatable: true' and not `executable: false` are listed

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-08-22 19:31 UTC, JeffreyThiessen approved these changes
Look great. Tested and working as intended. :+1:

2024-08-26 17:26 UTC, ChrisHuynh333 requested changes
If I have an automated workflow execution set up (when `executable` was `true`, and then its selected pipeline's `executable` is set to `false`, an error occurs if I go to edit the automated workflow execution.

2024-08-26 19:52 UTC, ChrisHuynh333 requested changes
Last one from me.
If a workflow execution is started, and the selected pipeline's `executable` is set to `false` while the workflow execution is in state `new/initial`, it will hang and stay in this state because the pipeline is no longer able to be found. In talking to Eric, the state should be updated to `error` in these cases.

You will want to add error handling to the `preparation_service` like we have for other services and add an appropriate message in case in the future, we want to display the error msg back to the user. You will also want to set `.cleaned = true` in order to for the WE to be deletable. We do not need to actually go through the `cleanup_service` as there is nothing that requires cleaning

2024-08-30 19:00 UTC, ericenns commented
> I changed it so that even if the automated workflow execution does not have an executable pipeline, they can still see it and can edit it. Should I instead change that to so they won't be able to see it if it's not executable?

I was thinking that we need some way to inform the user that the `automated_workflow_execution` will not work since it  is either no longer executable or automatable. For now I think your solution is sufficient, but I think it should be addressed in a follow up PR.

2024-09-04 14:25 UTC, ChrisHuynh333 requested changes
Works great! Just one last refactor from me

2024-09-04 14:25 UTC, ChrisHuynh333 commented on app/services/workflow_executions/preparation_service.rb
> +      end
Due to now needing an additional rubocop disable, I think we can just move checking `@pipeline.nil?`  into its own method.

Can you replace this with `return false unless validate_pipeline`

And then under `private`:
```
def validate_pipeline
      return true unless @pipeline.nil?

      @workflow_execution.state = :error
      @workflow_execution.cleaned = true
      @workflow_execution.save
      false
    end
```

2024-09-04 16:24 UTC, ChrisHuynh333 approved these changes
Looks good!

2024-09-09 16:37 UTC, deepsidhu85 requested changes
This is looking good just a few comments below

2024-09-09 16:37 UTC, deepsidhu85 commented on config/pipelines/pipelines.json
> +      {
Can we remove the `"executable": false` from this pipeline and change one of the earlier versions to include it instead? For testing purposes we probably want the newest version to be executable

2024-09-09 16:37 UTC, deepsidhu85 commented on app/services/workflow_executions/preparation_service.rb
> +    def validate_pipeline
We probably want to update the job to also set the state to error as the pipeline can be marked as non-executable after submission and before the preparation job actually runs

2024-09-10 16:44 UTC, deepsidhu85 approved these changes
Looks good to me!

2024-09-10 16:44 UTC, merged