Samples Table: Fixes preserving page size & number when toggling metadata
phac-nml/irida-next pull request #748
Opened 2024-09-10 19:53 UTC by ksierks

## What does this PR do and why?
_Describe in detail what your merge request does and why._
Fixes #737.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-09-12 13:01 UTC, joshsadam commented on config/initializers/pagy.rb
> +require 'pagy/extras/overflow'
**question:** Just curious on why you had to uncomment this, I could not see it being used.

2024-09-12 13:08 UTC, ericenns requested changes
This is not working as expected. Now `page` is preserved when searching which breaks last acceptance criteria for #736 and results in a weird url in the address bar.

![image](https://github.com/user-attachments/assets/1733adc1-ae4e-45f1-bac3-0efed2e25c8e)

I think that the metadata toggling will need to be moved into a separate form so that `page` param is not including in the search form.

2024-09-12 14:59 UTC, ksierks commented
> > > This is not working as expected.
> > 
> > 
> > What is not working as expected? From the end user point of view, I think it's doing what it's suppose to be doing. Your screenshot shows page 17 in the URL, because you were likely on page 17 before filtering. Aren't the results within the table correct? Once you clear the filter, the user sees page 1 again. I'm confused.
> 
> > > This is not working as expected.
> > 
> > 
> > What is not working as expected? From the end user point of view, I think it's doing what it's suppose to be doing. Your screenshot shows page 17 in the URL, because you were likely on page 17 before filtering. Aren't the results within the table correct? Once you clear the filter, the user sees page 1 again. I'm confused.
> 
> In issue #736, it specifies that `page` param should not be preserved when searching/filtering (e.g. search box or filter by samples names or Id.), in your previous pr the `page` param was not sent in the search form, but in this PR you send that param. By setting up the overflow, now the address bar `page` param does not match the currently displayed `page`.
> 
> The intention with not sending the `page` param while searching was so that the user would always be directed to the first page of results. With this current setup the `page` param is sent in the search form and the user is sent to the `last` page of results if the current page they are on overflows the pages after searching.

I think overflow should go to the last page. The reason the error is happening is because the user is currently on a page other than the first page. 

The user acceptance criteria is designed to come from the user's perspective. I think you meant to label it `Implementation Guide`, like in https://github.com/phac-nml/irida-next/issues/75. I tried re-reading the user acceptance criteria from the issue and there was no mention of moving the metadata toggle into it's own form. Only to add the page param to the current search form. 
![image](https://github.com/user-attachments/assets/54e635ad-c2dc-427f-b6a2-47784bb8bc1b).

I will try to re-implement it with this new information and move the metadata toggling into it's own form. Thanks.

2024-09-13 15:30 UTC, ericenns requested changes
This is now working as expected. Just one minor comment from me, otherwise this looks great

2024-09-13 15:30 UTC, ericenns commented on config/initializers/pagy.rb
**nitpick (blocking):** Could you revert this file to what it looks like in main branch

2024-09-13 16:04 UTC, ksierks commented on config/initializers/pagy.rb
31e8a941a9b797f0d4cad557051e5dda81f9c40a

2024-09-13 16:12 UTC, ericenns approved these changes
Looks good to me!

2024-09-13 16:13 UTC, joshsadam approved these changes
This works.  I think that is a pretty good solution.

2024-09-13 16:14 UTC, merged