Groups/samples_count
phac-nml/irida-next pull request #783
Opened 2024-09-25 03:12 UTC by malchua

## What does this PR do and why?
_Describe in detail what your merge request does and why._

This PR adds a samples_count column to Groups to show the total number of samples contained within a group. This also includes all samples in projects within subgroups.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._
![image](https://github.com/user-attachments/assets/a51a7983-adbf-437e-8340-bfb55b39101a)

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._
1. Sign in
2. Click on "Groups" on the sidebar
3. Find a group where you are the owner and take note of the number of samples listed (number next to the beaker icon)
4. Select the group
5. Look through "Subgroups and projects" and check that the number of samples is accumulating correctly as you move up from projects to subgroups or subgroups to the parent group
6. Compare the number of samples listed in step 3 and see that it equals the accumulated number from step 5
7. Select a project within that group
8. Click on "Samples" on the sidebar
9. Add a new sample to the project
10. Go back to the parent group and check to see that the number of samples increased by one
11. Repeat steps 8-10 but delete samples
12. Repeat steps 8-10 but clone samples
13. Repeat steps 8-10 but transfer samples
14. Click on "Projects" on the sidebar
15. Select a project where you are the owner
16. Select "Settings" -> "General" in the sidebar
17. Go to the Transfer project section and transfer the project to a different parent group
18. Click on "Projects" on the sidebar
19. Find the parent group and check that the sample counts are correct.
20. Go back into the same project and delete the project
21. Click on "Projects" on the sidebar
22. Find the parent group of the deleted project
23. Check that the sample counts are correct
24. Repeat steps 14-23 but transfer and delete a group instead

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-10-04 15:09 UTC, ChrisHuynh333 requested changes
A couple comments at first glance.

You'll want to add UI tests as well for each of the actions (ie: after deleting a sample, return to the group index page and verify the sample count in the group's table row is accurate).

2024-10-04 15:09 UTC, ChrisHuynh333 commented on db/migrate/20240925230422_add_samples_count_to_namespaces.rb
> +end
Much like how you had a migration to reset the sample counter for projects after adding the `samples_count` column to projects, you'll want a migration to set the current sample count of groups. If I were to seed my db on main, and then go to your branch and run the migration, my group sample counts are zero.

2024-10-16 17:04 UTC, deepsidhu85 commented
@malchua I was testing out your PR and came across this:

![image](https://github.com/user-attachments/assets/41bc3b18-d6b8-4a3b-bf35-3e82b414de34)

The number of samples is not being displayed for the projects on the `Subgroups and projects` tab when a group is expanded

2024-10-18 14:50 UTC, ChrisHuynh333 requested changes
@ericenns @deepsidhu85 Feel free to chime in if you guys don't feel the same about the following.

I think you'll have to add `group.samples_count` manually to all groups like you have for projects.

In addition, I'd add a test to each of group and project models to loop through all projects/groups and check the current fixture `samples_count` to the actual `samples_count` (retrieve the real samples_count from `Project.reset_counters` / your group scope). This will help keep everyone accountable to update the sample_counts as we continue to add samples to our fixtures and keep things accurate. Add a comment to each test with something like `If you've added samples to fixtures, update the sample_count to the corresponding project/group` as the project/group won't be specified when the test fails.

2024-10-18 14:50 UTC, ChrisHuynh333 commented on test/controllers/groups_controller_test.rb
> +    group = groups(:group_twelve)
After updating `group.samples_count` this change shouldn't be necessary.

2024-10-18 14:50 UTC, ChrisHuynh333 commented on test/controllers/groups_controller_test.rb
> +    group = groups(:group_twelve)
After updating `group.samples_count` this change shouldn't be necessary.

2024-10-18 14:50 UTC, ChrisHuynh333 commented on test/models/group_test.rb
> +  end
Didn't realize you had started this before writing the top comment, so yes change this to the above in my opinion.

2024-10-18 14:50 UTC, ChrisHuynh333 commented on test/services/samples/destroy_service_test.rb
> +      sample34 = samples(:sample34)
Could you refactor these into this test file's setup and remove the individual setups as many tests use these fixtures. Feel free to look through the other test files you worked in and make the same change if they're called many times as well.

2024-10-18 14:50 UTC, ChrisHuynh333 commented on test/system/groups_test.rb
>        assert_selector 'input[type=submit]:disabled'
Undo these changes after adding `group.samples_count`

2024-10-18 14:50 UTC, ChrisHuynh333 commented on app/services/groups/destroy_service.rb
> +                                      .select(:samples_count).pluck(:samples_count).sum
This should just be able to be `@deleted_samples_count = @group.samples_count`

2024-10-18 15:00 UTC, ericenns requested changes
I found a few edge cases where samples_count is not properly updated.

2024-10-18 15:00 UTC, ericenns commented on app/services/samples/transfer_service.rb
> +        update_samples_count(transferred_samples_ids.count) if @project.parent.type == 'Group'
**nitpick (blocking):** If I create a project under my user namespace with a sample, and then transfer that sample to a project that is under a group. The group does not update the sample count and it remains at 0.

2024-10-28 18:43 UTC, ChrisHuynh333 approved these changes
Looks good!

2024-10-29 16:24 UTC, ericenns approved these changes
Looks good to me!

2024-10-29 16:24 UTC, merged