Metadata: Update values to strings
phac-nml/irida-next pull request #808
Opened 2024-10-03 20:47 UTC by ksierks

## What does this PR do and why?
Converting metadata values to strings, so we can search all metadata values. (See #807.)
Fixes #771.

## Screenshots or screen recordings
![image](https://github.com/user-attachments/assets/0496192a-2c05-4cec-8f0d-0134ee7bd423)

## How to set up and validate locally
**Add metadata through the UI:**
1. Navigate to a samples page that the logged in user has access to update.
5. Hit the `Import Metadata` button.
6. Select a file. (See /irida-next-core/test/fixtures/files/metadata/valid.xlsx)
7. Select the `Sample ID` Column.
8. Hit the `Import Metadata` button.
9. Verify the sample metadata was added as strings.
10. Follow the `Test searching metadata` instructions below.

**Add metadata through GraphQL:**
1. Navigate to `http://localhost:3000` and login as admin.
2. Navigate to `http://localhost:3000/graphiql`.
3. Run the following to retrieve a project:
```
query getProject{
  project(fullPath: "bacillus/bacillus-anthracis/outbreak-2022") {
    id
    name
    path
  }
}
```
4. Run the following to create a fresh sample:
```
mutation createSample{
  createSample(input: { 
    projectId: "<insert here>", 
    name: "Sample Name", 
    description: "Sample Description" 
  }) {
    sample {
      id,
      puid,
      name,
      description
    }
    errors {
      path,
      message
    }
  }
}
```
5. Run the following to add metadata to the sample:
```
mutation addMetadataToSample{
  updateSampleMetadata(input: {
    sampleId: "<insert here>", 
    metadata: { true_boolean: true, false_boolean: false, nil: null, empty: "", number: 123, date: "2024-03-11" }
  }) {
    sample{
      id,
      name,
      description,
      metadata
    },
    status,
    errors {
      path
      message
    }
  }
}
```
6. Verify the date, number, true_boolean, and false_boolean were added successfully as strings.
7. Follow the `Test searching metadata` instructions below.

**Test searching metadata**
1. Navigate to a samples page.
2. Toggle metadata.
3. Search using the format FIELD_NAME:FIELD_VALUE.
4. Verify the results when searching for dates, numbers, booleans, etc. 
 
## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-10-09 18:56 UTC, JeffreyThiessen requested changes
Overall it looks good. Just one change, and add a test to verify it as well.

2024-10-09 18:56 UTC, JeffreyThiessen commented on app/services/samples/metadata/update_service.rb
> +          value = value.to_s # remove data types
Can you strip white space from the keys and values? I noticed that white space is also getting included when trying to look up the sample id from an xlsx file.

2024-10-10 17:02 UTC, JeffreyThiessen approved these changes
Looks great!

2024-10-10 17:08 UTC, ChrisHuynh333 approved these changes
Looks good!

2024-10-15 17:05 UTC, deepsidhu85 approved these changes
Looks good to me! Thanks for fixing up the migration

2024-10-15 17:05 UTC, merged