GraphQL: add queries for getting pipelines
phac-nml/irida-next pull request #830
Opened 2024-10-28 18:37 UTC by JeffreyThiessen

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-11-07 18:13 UTC, ChrisHuynh333 submitted a review, later dismissed
Looks good!

2024-11-22 15:16 UTC, ericenns requested changes
First pass of comments

2024-11-22 20:13 UTC, JeffreyThiessen commented on app/graphql/types/pipeline_type.rb
> +  class PipelineType < Types::BaseType
fixed in https://github.com/phac-nml/irida-next/pull/830/commits/416ff3d7a5bcd374217c41c9a610187f074efba3

2024-11-22 20:13 UTC, JeffreyThiessen commented on app/graphql/resolvers/pipelines_resolver.rb
> +    type Types::PipelineType.connection_type, null: true
fixed in https://github.com/phac-nml/irida-next/pull/830/commits/416ff3d7a5bcd374217c41c9a610187f074efba3

2024-11-22 20:13 UTC, JeffreyThiessen commented on app/graphql/types/pipeline_type.rb
> +    implements GraphQL::Types::Relay::Node
fixed in https://github.com/phac-nml/irida-next/pull/830/commits/416ff3d7a5bcd374217c41c9a610187f074efba3

2024-11-22 20:13 UTC, JeffreyThiessen commented on app/graphql/types/query_type.rb
> +    field :pipelines, Types::PipelineType.connection_type, null: true, resolver: Resolvers::PipelinesResolver,
fixed in https://github.com/phac-nml/irida-next/pull/830/commits/416ff3d7a5bcd374217c41c9a610187f074efba3

2024-11-26 13:29 UTC, ericenns approved these changes
Looks good to me!

2024-11-26 13:29 UTC, merged