Graphql: Submit Workflow Execution
phac-nml/irida-next pull request #838
Opened 2024-11-07 23:31 UTC by JeffreyThiessen

## What does this PR do and why?
_Describe in detail what your merge request does and why._

Dependant on #832 

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

```graphql
mutation submitWE {
  submitWorkflowExecution (input:{
    name:"My Workflow from graphql 3"
    projectId: "gid://irida/Project/8fabf522-9757-4b51-a0bb-3f0228566f8a"
    updateSamples: false
    emailNotification: false
    workflowName: "phac-nml/iridanextexample"
    workflowVersion:"1.0.3"
    workflowParams: {
      assembler: "stub",
      random_seed: 1,
      project_name: "assembly"
    }
    workflowType: "NFL"
    workflowTypeVersion:"DSL2"
    workflowEngine:"nextflow"
    workflowEngineVersion: "23.10.0"
    workflowEngineParameters: [
      {
        key:"-r",
        value:"1.0.3"
      }
    ]
    workflowUrl: "https://github.com/phac-nml/iridanextexample"
    samplesFilesInfoList:[
      {
        sample_id:"gid://irida/Sample/ad45bc69-a176-4395-a4c9-057a6f17f6f3"
        files:[
          {
            file_type: "fastq_1"
            file_id: "gid://irida/Attachment/e0cff8a5-122e-445b-9f97-34831a67b7c4"
          },
          {
            file_type: "fastq_2"
            file_id: "gid://irida/Attachment/0856eff8-f822-489e-a34a-ed0caaf064d1"
          }
        ]
      }
    ]
  }){
		workflowExecution{
      name
      id
    }
    errors{
      message
      path
    }
  }
}
```

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2025-01-09 17:57 UTC, ChrisHuynh333 approved these changes
Looks good and works as described!

2025-01-10 13:49 UTC, ericenns requested changes
I tried resetting the database on this branch but it failed due to the new validation of `samplesheet_params` can you please update the `seed_workflow_executions` method in `db/seeds.rb` so that this error no longer occurs.

Note: I only figured out that was the case after changing `WorkflowExecution.create` to `WorkflowExecution.create!` which causes an exception to be raised when the record is unable to be saved. Without that it was failing on line 197 in `db/seeds.rb` as it could not create the attachment without `attachable_id`

2025-01-10 18:12 UTC, JeffreyThiessen commented
> I tried resetting the database on this branch but it failed due to the new validation of `samplesheet_params` can you please update the `seed_workflow_executions` method in `db/seeds.rb` so that this error no longer occurs.
> 
> Note: I only figured out that was the case after changing `WorkflowExecution.create` to `WorkflowExecution.create!` which causes an exception to be raised when the record is unable to be saved. Without that it was failing on line 197 in `db/seeds.rb` as it could not create the attachment without `attachable_id`

Fixed in https://github.com/phac-nml/irida-next/pull/838/commits/02e498e3d68ebbe46aef99acc0c76fb21a5ba7b5

2025-01-13 15:38 UTC, ericenns requested changes
This is looking good. Just a few comments and could you review the rubocop warnings present in the `Files changed` tab.

2025-01-13 15:38 UTC, ericenns commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :name, String, description: 'Name for the new workflow.'
**nitpick (blocking):** Can you change this to optional as it currently is when submitting a workflow execution through the UI

2025-01-13 15:38 UTC, ericenns commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :email_notification, Boolean,
**nitpick (blocking):** Can you change this to optional, and set a default value of `false`.

2025-01-13 15:38 UTC, ericenns commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :update_samples, Boolean, description: 'Set true for samples to be updated from this workflow execution' # rubocop:disable GraphQL/ExtractInputType
**nitpick (blocking):** Can you set this to optional and set a default value of `false`.

2025-01-13 22:43 UTC, JeffreyThiessen commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :update_samples, Boolean, description: 'Set true for samples to be updated from this workflow execution' # rubocop:disable GraphQL/ExtractInputType
Fixed in https://github.com/phac-nml/irida-next/pull/838/commits/e7fff0f15273f5103f471bd6b2475fdc2e88351d

2025-01-13 22:43 UTC, JeffreyThiessen commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :email_notification, Boolean,
Fixed in https://github.com/phac-nml/irida-next/pull/838/commits/e7fff0f15273f5103f471bd6b2475fdc2e88351d

2025-01-13 22:44 UTC, JeffreyThiessen commented on app/graphql/mutations/submit_workflow_execution.rb
> +    argument :name, String, description: 'Name for the new workflow.'
Fixed in https://github.com/phac-nml/irida-next/pull/838/commits/e7fff0f15273f5103f471bd6b2475fdc2e88351d

2025-01-15 16:12 UTC, deepsidhu85 commented
While testing this PR out, I was able to use this for the samplesWorkflowExecutionAttributes JSON for the mutation which worked but it shouldn't have

```
{"samples_workflow_executions_attributes": {"sample_id": "gid://irida/Sample/c9427c0f-51e2-45b8-828c-6d32113eb679","samplesheet_params": {"sample": "INXT_SAM_AZBO256QCZ","fastq_1": "gid://irida/Attachment/141ea970-db29-4a97-9953-937986ff3ec5","fastq_2": "gid://irida/Attachment/f1179ccd-2308-4fb5-bb8b-25a900e387b5"}}}
```

Looks like we need to add validation to make sure that the `sample_id` and `sample` belong to the project that was set for the mutation, and validate that the attachments belong to this sample.

The reason the above shouldn't have worked is because the `sample_id` and `sample` don't belong to the project that was set in the mutation, and the attachments also do not belong to this sample

Steps to recreate:

Seed db if you already don't have it seeded
Login as `admin@email.com`
Create a new project, sample, and upload a paired-end dataset
Run the `submitWorkflowExecution` mutation using `http://localhost:3000/graphiql`  with the changes listed below the mutation:

```
 mutation($samples_workflow_executions_attributes: [JSON!]!){
      submitWorkflowExecution( input:{
        name: "testWE"
        projectId: "gid://irida/Project/b92623f7-6dc5-4ab6-a520-bf539b46a78a"
        updateSamples: false
        emailNotification: false
        workflowName: "phac-nml/iridanextexample"
        workflowVersion: "1.0.3"
        workflowParams: {
          assembler: "stub",
          random_seed: 1,
          project_name: "assembly"
        }
        workflowType: "NFL"
        workflowTypeVersion:"DSL2"
        workflowEngine:"nextflow"
        workflowEngineVersion: "23.10.0"
        workflowEngineParameters: [
          {
            key:"-r",
            value:"1.0.3"
          }
        ]
        workflowUrl: "https://github.com/phac-nml/iridanextexample"
        samplesWorkflowExecutionsAttributes: $samples_workflow_executions_attributes
        }) {
        workflowExecution{
          name
          id
        }
        errors{
          message
          path
        }
      }
    }
```

set the project_id to global id of created project above

In the hash for `samplesWorkflowExecutionsAttributes`, set the `sample_id` to a global id of a sample from another project, and set the `sample` with the puid of this sample. Set the `fastq_1` and `fastq_2` to the global ids of the attachments you uploaded above

Run the query and it should succeed.

2025-01-15 22:43 UTC, deepsidhu85 approved these changes
Looks good to me!

2025-01-16 13:44 UTC, ericenns approved these changes
Looks good to me!

2025-01-16 13:45 UTC, merged