Data Table: Bot Accounts
phac-nml/irida-next pull request #849
Opened 2024-11-22 19:29 UTC by ChrisHuynh333

## What does this PR do and why?
_Describe in detail what your merge request does and why._

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-12-04 14:52 UTC, joshsadam requested changes
This looks really great overall.  I actually only have one wording change I would like to see.

2024-12-04 16:22 UTC, ChrisHuynh333 commented on config/locales/en.yml
> +          remove: Delete bot
Agreed, changed in 90e8c7ed61effaa857e6a5de0cb6f0ef6097b8e2.

I've also changed the key from `remove` to `destroy` as that lines up more with what we've done for other translations.

2024-12-09 20:47 UTC, deepsidhu85 submitted a review, later dismissed
Looks good to me!

2024-12-19 01:06 UTC, joshsadam commented
I found a minor UI bug that I am hoping you can fix, and I am hoping that I can explain it properly. I will paste the screenshot and try to explain below.
![bots](https://github.com/user-attachments/assets/fbce4564-4850-447b-a44f-8c8f372696aa)

- The div highlighted in the developer console wraps a `turbo-frame`.
- When the turbo frame is empty (as in the screenshot) the div is empty but still renders and has the class of `mb-4` which for all purposes makes the margin bottom on the header 8.
- Can you remove the wrapping div and set the `mb-4` on the content within the `turbo-frame` so that it is only there if the `turbo-frame` has content?

2024-12-19 01:10 UTC, joshsadam commented
I think this small bug is something that you can quickly fix in this PR.  The create  bot modal body does not vertically scroll.  If you don't have enough vertical screen space you cannot fill in all the values.  As yo can see in the screenshot I cannot select a date 
![image](https://github.com/user-attachments/assets/5f5fc71c-a55d-45d7-84a9-005cda56535f)

2024-12-19 01:17 UTC, joshsadam requested changes
This looks good.  I left 2 comments that I am hoping you can quickly fix. Good work on this.

2024-12-19 15:13 UTC, ChrisHuynh333 commented
> I found a minor UI bug that I am hoping you can fix, and I am hoping that I can explain it properly. I will paste the screenshot and try to explain below. ![bots](https://private-user-images.githubusercontent.com/11295750/397177725-fbce4564-4850-447b-a44f-8c8f372696aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjE0ODQsIm5iZiI6MTczNDYyMTE4NCwicGF0aCI6Ii8xMTI5NTc1MC8zOTcxNzc3MjUtZmJjZTQ1NjQtNDg1MC00NDdiLWE0NGYtOGM4ZjM3MjY5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE1MTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjAxMDZkM2EwYmRmOTcwMzI1MWFkNTg1YzQwNmE5NGE3NDA0ZjU4M2RkNTZiYjI0NjI2OTVhZTRjYTcyNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4jXUXfZTLdsDrabfFuXL5fSAbZD1m8p-vRDHM9aKXsQ)
> 
> * The div highlighted in the developer console wraps a `turbo-frame`.
> * When the turbo frame is empty (as in the screenshot) the div is empty but still renders and has the class of `mb-4` which for all purposes makes the margin bottom on the header 8.
> * Can you remove the wrapping div and set the `mb-4` on the content within the `turbo-frame` so that it is only there if the `turbo-frame` has content?

Thanks, removed the wrapper and moved the `mb-4` to the frame content for both projects and groups in f039c402c4192177e1202278e122a8123f25ffa6

2024-12-19 16:59 UTC, joshsadam approved these changes
This looks good to me

2024-12-19 18:07 UTC, merged