Update: Group samples count calculation should include shared groups and projects
phac-nml/irida-next pull request #862
Opened 2024-12-06 01:08 UTC by malchua

## What does this PR do and why?
_Describe in detail what your merge request does and why._
This PR changes the sample count of a group to incorporate sample counts from it's shared groups and projects. This update will allow the samples count to properly reflect the amount of samples shown after clicking samples on the sidebar for a group.

## Screenshots or screen recordings
_Screenshots are required for UI changes, and strongly recommended for all other pull requests._

## How to set up and validate locally
_Numbered steps to set up and validate the change are strongly suggested._
General check:
1. Click on Groups in the sidebar.
2. Take note of the samples count for any group that you know has a group or project shared with it. Click on that group.
3. Click on Samples in the sidebar.
4. At the bottom of the page, there is a section saying "Display 1-20 of X items" where X is the total number of samples this group has access to. Confirm that this number equals the one noted in step 2.

Sharing a project:
1. Click on Groups in the sidebar.
2. Take note of the samples count for any group that you have access to.
3. Click on Projects in the sidebar.
4. Select a project that you own, that has not already been shared to the group in step 2.
5. Click on Members in the sidebar.
6. Select the "Invite group" button.
7. Select the group that was noted in step 2, and give it an access level of Analyst. Click "Share".
8. Repeat the general check above with the group selected in step 2. The samples count should have increase by the direct samples count** of the project we shared. 

Sharing a group:
1. Click on Groups in the sidebar.
2. Take note of the samples count for any group that you have access to.
3. Select a different group that you have access to and want to share with the group in step 2. This different group should not already be shared with the group in step 2.
5. Click on Members in the sidebar.
6. Select the "Invite group" button.
7. Select the group that was noted in step 2, and give it an access level of Analyst. Click "Share".
8. Repeat the general check above with the group selected in step 2. The samples count should have increase by the direct samples count** of the group we shared. 

**Direct samples count for a shared project = samples count of that project
**Direct samples count for a shared group = the sum of all samples found within projects in itself and it's ancestor groups. (This does not include the samples count of projects or groups that have been shared with it)

## PR acceptance checklist
This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] I have evaluated the [PR acceptance checklist](https://phac-nml.github.io/irida-next/docs/development/development_processes/code_review#acceptance-checklist) for this PR.

2024-12-20 00:47 UTC, JeffreyThiessen requested changes
Looks good and is working as specified. Just one small change.

2024-12-20 00:47 UTC, JeffreyThiessen commented on app/models/group.rb
> +  def aggregated_samples_count # rubocop:disable Metrics/AbcSize
Nitpick: Please change the order of the first 2 lines of the function to
```
return sample_count unless shared_namespaces.any?

aggregated_samples_count = samples_count
```
This way the first line is the early return from the function, and we do not have to create/assign the new variable before doing so.

2024-12-30 17:31 UTC, JeffreyThiessen approved these changes
Looks good to me :+1:

2025-01-03 13:25 UTC, ericenns requested changes
This is looking great, just one small comment.

Can you change line 15 in `app/controllers/groups/samples_controller.rb` to use `aggregated_samples_count` instead of the query it is currently doing.

2025-01-07 14:28 UTC, ericenns submitted a review, later dismissed
One minor comment, but also could you review and fix the rubocop warnings in `app/models/group.rb`

2025-01-08 13:54 UTC, ericenns requested changes
This is looking great, just only one minor comment and then this can be merged in.

2025-01-08 13:54 UTC, ericenns commented on app/models/group.rb
**nitpick (blocking):** Can you remove the added associations since they are not being used anywhere.

2025-01-08 17:12 UTC, ericenns approved these changes
Looks good to me!

2025-01-08 17:12 UTC, merged